from io import BytesIO
from datetime import datetime

from reportlab.lib.colors import HexColor
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)


def create_chat_pdf(messages):

    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    title = styles["Heading1"]
    title.alignment = TA_CENTER
    title.textColor = HexColor("#2563EB")

    heading = styles["Heading2"]

    normal = styles["BodyText"]

    story = []

    # -----------------------------
    # Title
    # -----------------------------

    story.append(

        Paragraph(

            "🤖 RAG Website Chatbot",

            title

        )

    )

    story.append(
        Spacer(1, 20)
    )

    story.append(

        Paragraph(

            f"<b>Generated:</b> {datetime.now().strftime('%d %B %Y %H:%M:%S')}",

            normal

        )

    )

    story.append(
        Spacer(1, 20)
    )

    # -----------------------------
    # Conversation
    # -----------------------------

    story.append(

        Paragraph(

            "Conversation",

            heading

        )

    )

    story.append(
        Spacer(1, 10)
    )

    question_count = 0

    answer_count = 0

    for message in messages:

        role = message.get("role", "")

        text = message.get("text", "")

        if role == "user":

            question_count += 1

            story.append(

                Paragraph(

                    "<b>🧑 You</b>",

                    normal

                )

            )

        else:

            answer_count += 1

            story.append(

                Paragraph(

                    "<b>🤖 Assistant</b>",

                    normal

                )

            )

        story.append(

            Paragraph(

                text.replace("\n", "<br/>"),

                normal

            )

        )

        # -------------------------
        # Sources
        # -------------------------

        if "sources" in message:

            story.append(
                Spacer(1, 5)
            )

            story.append(

                Paragraph(

                    "<b>Sources</b>",

                    normal

                )

            )

            for source in message["sources"]:

                story.append(

                    Paragraph(

                        f"• {source['source_file']} | Chunk {source['chunk_id']}",

                        normal

                    )

                )

        story.append(
            Spacer(1, 15)
        )

    # -----------------------------
    # Statistics
    # -----------------------------

    story.append(
        Spacer(1, 10)
    )

    story.append(

        Paragraph(

            "Conversation Statistics",

            heading

        )

    )

    story.append(

        Paragraph(

            f"Questions : {question_count}",

            normal

        )

    )

    story.append(

        Paragraph(

            f"Answers : {answer_count}",

            normal

        )

    )

    story.append(

        Paragraph(

            f"Total Messages : {len(messages)}",

            normal

        )

    )

    story.append(
        Spacer(1, 20)
    )

    story.append(

        Paragraph(

            "<i>Generated by RAG Website Chatbot</i>",

            normal

        )

    )

    doc.build(story)

    pdf = buffer.getvalue()

    buffer.close()

    return pdf